#!/usr/bin/env ruby

require "beeminder"
require "trollop"

class Hash
  def map_values
    Hash[map{|k,v| [k, yield(v)]}]
  end
end

class Date
  # Week starts of Monday, not Sunday
  def real_wday
    if wday == 0
      6
    else
      wday - 1
    end
  end
  def first_weekday
    self - real_wday
  end
end

class Beeminder::User
  def active_goals
    goals.select{|g|
      g.days_to_lose >= 0 && g.goal_type == :hustler
    }
  end
end

class Beeminder::Goal
  def days_to_lose
    (losedate.to_date - Date.today).to_i
  end
  def goal_time
    (Time.now.to_i - @initday)/(3600*24) + 1
  end
end

class Beeminder::Datapoint
  def date
    timestamp.to_date
  end
  def relative_value
    value / goal.curval
  end
  def blank?
    value == 0
  end
end

class BeeminderTrends
  def initialize(verbose)
    @verbose = verbose
  end

  def report_datapoint(date, values)
    total = values.values.sum
    details = values.sort_by{|k,v| [-v,k]}.map{|k,v| "%s:%.2f" % [k, v]}.join(" ")

    if @verbose
      puts "#{date}  #{'%.2f' % total}  #{details}"
    else
      puts "#{date}  #{'%.2f' % total}"
    end
  end

  def token
    @token ||= File.read("#{ENV["HOME"]}/.beeminder_auth_token").chomp
  end

  def goals
    @active_goals ||= Beeminder::User.new(token).active_goals
  end

  def each_datapoint
    goals.each do |goal|
      goal.datapoints.reject(&:blank?).each do |dp|
        yield(dp)
      end
    end
  end

  def weekly_report_range(values_by_week)
    start_date = values_by_week.keys.min
    end_date   = [Date.today.first_weekday, *values_by_week.keys].max
    (start_date..end_date).to_a.select(&:monday?)
  end

  def report_weekly!
    values_by_week = Hash.new{|ht,k| ht[k] = Hash.new(0)}

    each_datapoint do |dp|
      values_by_week[dp.date.first_weekday][dp.goal.slug] += dp.relative_value
    end

    range = weekly_report_range(values_by_week)
    scale = 7 * range.size / goals.size

    range.each do |d|
      report_datapoint(d.strftime("%Y-%m-%d"), values_by_week[d].map_values{|x| x*scale})
    end
  end

  def daily_report_range(values_by_day)
    start_date = values_by_day.keys.min
    end_date   = [Date.today, *values_by_day.keys].max
    (start_date..end_date).to_a
  end

  def report_daily!
    values_by_day = Hash.new{|ht,k| ht[k] = Hash.new(0)}

    each_datapoint do |dp|
      values_by_day[dp.date][dp.goal.slug] += dp.relative_value
    end

    range = daily_report_range(values_by_day)
    scale = range.size / goals.size

    range.each do |d|
      report_datapoint(d.strftime("%Y-%m-%d %a"), values_by_day[d].map_values{|x| x*scale})
    end
  end
end

opts = Trollop::options do
  opt :verbose, "Print subtotal contributions"
  opt :weekly, "Aggregate data weekly"
end

bt = BeeminderTrends.new(opts[:verbose])

if opts[:weekly]
  bt.report_weekly!
else
  bt.report_daily!
end
